name: ultralight-api
region: nyc
services:
  - name: api
    dockerfile_path: Dockerfile
    github:
      repo: evrydayimruslin/ultralight
      branch: main
      deploy_on_push: true
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      # All secret values are injected via DigitalOcean App Platform dashboard.
      # Do NOT commit actual values here. Set them in:
      #   DigitalOcean > Apps > ultralight-api > Settings > Environment Variables
      - key: SUPABASE_URL
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        type: SECRET
      - key: SUPABASE_ANON_KEY
        type: SECRET
      - key: R2_ACCOUNT_ID
        type: SECRET
      - key: R2_ACCESS_KEY_ID
        type: SECRET
      - key: R2_SECRET_ACCESS_KEY
        type: SECRET
      - key: R2_BUCKET_NAME
        type: SECRET
    health_check:
      http_path: /health
      port: 8000
