import type { MCPTool } from './mcp.ts';

export interface UltralightConfig {
  apiUrl?: string;
  token: string;
}

export interface UploadFilePayload {
  path: string;
  content: string;
  encoding?: 'text' | 'base64';
}

export interface CreateAppOptions {
  name?: string;
  slug?: string;
  description?: string;
  visibility?: 'private' | 'unlisted' | 'public';
  files: UploadFilePayload[];
  autoGenerateDocs?: boolean;
}

export interface UpdateAppOptions {
  name?: string;
  description?: string;
  visibility?: 'private' | 'unlisted' | 'public';
  category?: string;
  tags?: string[];
}

export interface ListAppsOptions {
  visibility?: 'all' | 'public' | 'private' | 'unlisted';
  limit?: number;
  offset?: number;
  includeDrafts?: boolean;
}

export interface DraftUploadOptions {
  files: UploadFilePayload[];
}

export interface PublishOptions {
  regenerateDocs?: boolean;
  versionBump?: 'patch' | 'minor' | 'major';
}

export interface DiscoverOptions {
  limit?: number;
  includePrivate?: boolean;
  minSimilarity?: number;
}

export interface RunOptions {
  useDraft?: boolean;
}

export interface AppSummary {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  visibility: 'private' | 'unlisted' | 'public';
  current_version: string;
  exports: string[];
  total_runs: number;
  runs_30d: number;
  mcp_endpoint: string;
  app_url: string;
  created_at: string;
  updated_at: string;
}

export interface RunResult {
  success: boolean;
  result: unknown;
  error?: string;
  logs?: Array<{ message: string }>;
  duration_ms: number;
}

export interface DiscoverResult {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  similarity: number;
  is_owner: boolean;
  mcp_endpoint: string;
}

export interface PlatformUserProfile {
  id: string;
  email: string;
  display_name: string | null;
  tier: string;
}

export interface RpcToolResultEnvelope {
  content?: Array<{ type: string; text?: string }>;
  structuredContent?: unknown;
  isError?: boolean;
}

export type { MCPTool };
