/**
 * Ultralight SDK
 *
 * TypeScript SDK for programmatic access to Ultralight platform.
 *
 * @example
 * ```typescript
 * import { Ultralight } from 'ultralightpro-sdk';
 *
 * const ul = new Ultralight({ token: 'your-token' });
 *
 * // List apps
 * const apps = await ul.apps.list();
 *
 * // Create an app
 * const app = await ul.apps.create({
 *   name: 'My App',
 *   files: [{ path: 'index.ts', content: 'export function hello() { return "Hello!"; }' }]
 * });
 *
 * // Run a function
 * const result = await ul.run(app.app_id, 'hello');
 * ```
 */

export interface UltralightConfig {
  /** API base URL (default: https://api.ultralight.dev) */
  apiUrl?: string;
  /** Authentication token (JWT or API key) */
  token: string;
}

export interface CreateAppOptions {
  name?: string;
  slug?: string;
  description?: string;
  visibility?: 'private' | 'unlisted' | 'public';
  files: Array<{
    path: string;
    content: string;
    encoding?: 'text' | 'base64';
  }>;
  autoGenerateDocs?: boolean;
}

export interface UpdateAppOptions {
  name?: string;
  description?: string;
  visibility?: 'private' | 'unlisted' | 'public';
  category?: string;
  tags?: string[];
}

export interface ListAppsOptions {
  visibility?: 'all' | 'public' | 'private' | 'unlisted';
  limit?: number;
  offset?: number;
  includeDrafts?: boolean;
}

export interface DraftUploadOptions {
  files: Array<{
    path: string;
    content: string;
    encoding?: 'text' | 'base64';
  }>;
}

export interface PublishOptions {
  regenerateDocs?: boolean;
  versionBump?: 'patch' | 'minor' | 'major';
}

export interface DiscoverOptions {
  limit?: number;
  includePrivate?: boolean;
  minSimilarity?: number;
}

export interface RunOptions {
  useDraft?: boolean;
}

export interface App {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  visibility: 'private' | 'unlisted' | 'public';
  current_version: string;
  exports: string[];
  total_runs: number;
  runs_30d: number;
  mcp_endpoint: string;
  app_url: string;
  created_at: string;
  updated_at: string;
}

export interface RunResult {
  success: boolean;
  result: unknown;
  error?: string;
  logs?: Array<{ message: string }>;
  duration_ms: number;
}

export interface DiscoverResult {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  similarity: number;
  is_owner: boolean;
  mcp_endpoint: string;
}

export interface McpTool {
  name: string;
  description: string;
  inputSchema: unknown;
}

const DEFAULT_API_URL = 'https://api.ultralight.dev';

function normalizeToolArgs(args: unknown): Record<string, unknown> {
  if (!args) return {};
  if (typeof args === 'object' && !Array.isArray(args)) {
    return args as Record<string, unknown>;
  }
  return { value: args };
}

/**
 * Main Ultralight SDK client
 */
export class Ultralight {
  private apiUrl: string;
  private token: string;
  private requestId = 0;

  /** App management methods */
  readonly apps: AppsClient;
  /** Draft management methods */
  readonly drafts: DraftsClient;
  /** Documentation methods */
  readonly docs: DocsClient;

  constructor(config: UltralightConfig) {
    this.apiUrl = config.apiUrl || DEFAULT_API_URL;
    this.token = config.token;

    this.apps = new AppsClient(this);
    this.drafts = new DraftsClient(this);
    this.docs = new DocsClient(this);
  }

  /**
   * Execute a function in an app
   */
  async run(appId: string, functionName: string, args?: unknown, options?: RunOptions): Promise<RunResult> {
    const response = await this.callTool('ul.call', {
      app_id: appId,
      function_name: functionName,
      args: normalizeToolArgs(args),
      use_draft: options?.useDraft,
    });
    return {
      success: true,
      result: (response as { result?: unknown }).result ?? response,
      duration_ms: 0,
    };
  }

  /**
   * Discover apps by capability
   */
  async discover(query: string, options?: DiscoverOptions): Promise<DiscoverResult[]> {
    const result = await this.callTool('ul.discover', {
      scope: 'appstore',
      query,
      limit: options?.limit,
      min_similarity: options?.minSimilarity,
    });
    return (result as { results: DiscoverResult[] }).results;
  }

  /**
   * Get current user profile
   */
  async getUser(): Promise<{
    id: string;
    email: string;
    display_name: string | null;
    tier: string;
  }> {
    return this.restGet('/api/user') as Promise<{
      id: string;
      email: string;
      display_name: string | null;
      tier: string;
    }>;
  }

  /**
   * Create an MCP client for a specific app
   */
  mcp(appId: string): McpClient {
    return new McpClient(this.apiUrl, this.token, appId);
  }

  /**
   * Internal: Call a platform MCP tool
   * @internal
   */
  async callTool(name: string, args: Record<string, unknown>): Promise<unknown> {
    const response = await fetch(`${this.apiUrl}/mcp/platform`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.token}`,
      },
      body: JSON.stringify({
        jsonrpc: '2.0',
        id: ++this.requestId,
        method: 'tools/call',
        params: { name, arguments: args },
      }),
    });

    if (!response.ok) {
      throw new UltralightError(`API error: ${response.status}`, response.status);
    }

    const rpc = await response.json() as JsonRpcResponse;

    if (rpc.error) {
      throw new UltralightError(rpc.error.message, rpc.error.code);
    }

    if (rpc.result?.isError) {
      throw new UltralightError(rpc.result.content?.[0]?.text || 'Unknown error');
    }

    return rpc.result?.structuredContent ?? {};
  }

  /** @internal */
  async restGet(path: string): Promise<unknown> {
    return this.restRequest('GET', path);
  }

  /** @internal */
  async restPost(path: string, body?: unknown): Promise<unknown> {
    return this.restRequest('POST', path, body);
  }

  /** @internal */
  async restPatch(path: string, body?: unknown): Promise<unknown> {
    return this.restRequest('PATCH', path, body);
  }

  /** @internal */
  async restDelete(path: string): Promise<unknown> {
    return this.restRequest('DELETE', path);
  }

  /** @internal */
  async restText(path: string): Promise<string> {
    const response = await fetch(`${this.apiUrl}${path}`, {
      method: 'GET',
      headers: { 'Authorization': `Bearer ${this.token}` },
    });
    if (!response.ok) {
      throw new UltralightError(`API error: ${response.status}`, response.status);
    }
    return response.text();
  }

  private async restRequest(method: string, path: string, body?: unknown): Promise<unknown> {
    const response = await fetch(`${this.apiUrl}${path}`, {
      method,
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.token}`,
      },
      body: body === undefined ? undefined : JSON.stringify(body),
    });

    if (!response.ok) {
      throw new UltralightError(`API error: ${response.status}`, response.status);
    }

    const text = await response.text();
    return text ? JSON.parse(text) : {};
  }
}

interface JsonRpcResponse {
  jsonrpc: '2.0';
  id: number;
  result?: {
    content?: Array<{ type: string; text?: string }>;
    structuredContent?: unknown;
    isError?: boolean;
  };
  error?: {
    code: number;
    message: string;
  };
}

/**
 * Apps client for managing Ultralight apps
 */
class AppsClient {
  constructor(private client: Ultralight) {}

  /**
   * List apps owned by the authenticated user
   */
  async list(options?: ListAppsOptions): Promise<{ apps: App[]; total: number }> {
    const payload = await this.client.restGet('/api/apps/me');
    const apps = Array.isArray(payload) ? payload as App[] : (payload as { apps?: App[] }).apps ?? [];
    const visible = options?.visibility && options.visibility !== 'all'
      ? apps.filter((app) => app.visibility === options.visibility)
      : apps;
    const offset = options?.offset ?? 0;
    const limit = options?.limit ?? visible.length;
    return { apps: visible.slice(offset, offset + limit), total: visible.length };
  }

  /**
   * Get details for a specific app
   */
  async get(appId: string, options?: { includeCode?: boolean; includeSkills?: boolean }): Promise<App & { code?: string; skills_md?: string }> {
    const app = await this.client.restGet(`/api/apps/${encodeURIComponent(appId)}`) as App & { code?: string; skills_md?: string };
    if (options?.includeCode) {
      const code = await this.client.restGet(`/api/apps/${encodeURIComponent(appId)}/code`) as { code?: string };
      app.code = code.code;
    }
    if (options?.includeSkills) {
      app.skills_md = await this.client.restText(`/api/apps/${encodeURIComponent(appId)}/skills.md`);
    }
    return app;
  }

  /**
   * Create a new app
   */
  async create(options: CreateAppOptions): Promise<{
    app_id: string;
    slug: string;
    version: string;
    url: string;
    exports: string[];
    docs_generated?: boolean;
  }> {
    return this.client.callTool('ul.upload', {
      type: 'app',
      name: options.name,
      slug: options.slug,
      description: options.description,
      visibility: options.visibility,
      auto_generate_docs: options.autoGenerateDocs,
      files: options.files,
    }) as Promise<{
      app_id: string;
      slug: string;
      version: string;
      url: string;
      exports: string[];
      docs_generated?: boolean;
    }>;
  }

  /**
   * Update app metadata
   */
  async update(appId: string, updates: UpdateAppOptions): Promise<{ success: boolean }> {
    return this.client.restPatch(`/api/apps/${encodeURIComponent(appId)}`, updates) as Promise<{ success: boolean }>;
  }

  /**
   * Delete an app (soft delete)
   */
  async delete(appId: string): Promise<{ success: boolean }> {
    return this.client.restDelete(`/api/apps/${encodeURIComponent(appId)}`) as Promise<{ success: boolean }>;
  }

  /**
   * Search apps by text
   */
  async search(query: string, options?: { limit?: number; offset?: number }): Promise<{ results: App[]; total: number }> {
    const result = await this.client.callTool('ul.discover', {
      scope: 'appstore',
      query,
      limit: options?.limit,
    }) as { results?: App[] };
    const results = result.results ?? [];
    const offset = options?.offset ?? 0;
    return { results: results.slice(offset), total: results.length };
  }
}

/**
 * Drafts client for managing app drafts
 */
class DraftsClient {
  constructor(private client: Ultralight) {}

  /**
   * Upload a draft for an existing app
   */
  async upload(appId: string, options: DraftUploadOptions): Promise<{
    app_id: string;
    draft_version: string;
    exports: string[];
  }> {
    return this.client.restPost(`/api/apps/${encodeURIComponent(appId)}/draft`, {
      files: options.files,
    }) as Promise<{
      app_id: string;
      draft_version: string;
      exports: string[];
    }>;
  }

  /**
   * Get draft status for an app
   */
  async get(appId: string, options?: { includeDiff?: boolean }): Promise<{
    has_draft: boolean;
    draft_version?: string;
    draft_uploaded_at?: string;
    exports_diff?: {
      added: string[];
      removed: string[];
    };
  }> {
    return this.client.restGet(
      `/api/apps/${encodeURIComponent(appId)}/draft${options?.includeDiff ? '?include_diff=1' : ''}`,
    ) as Promise<{
      has_draft: boolean;
      draft_version?: string;
      draft_uploaded_at?: string;
      exports_diff?: { added: string[]; removed: string[] };
    }>;
  }

  /**
   * Publish a draft to production
   */
  async publish(appId: string, options?: PublishOptions): Promise<{
    success: boolean;
    previous_version: string;
    new_version: string;
    docs_regenerated: boolean;
  }> {
    return this.client.restPost(`/api/apps/${encodeURIComponent(appId)}/publish`, {
      regenerate_docs: options?.regenerateDocs,
      version_bump: options?.versionBump,
    }) as Promise<{
      success: boolean;
      previous_version: string;
      new_version: string;
      docs_regenerated: boolean;
    }>;
  }

  /**
   * Discard a draft
   */
  async discard(appId: string): Promise<{ success: boolean }> {
    return this.client.restDelete(`/api/apps/${encodeURIComponent(appId)}/draft`) as Promise<{ success: boolean }>;
  }
}

/**
 * Docs client for managing app documentation
 */
class DocsClient {
  constructor(private client: Ultralight) {}

  /**
   * Generate documentation from app code
   */
  async generate(appId: string, options?: { aiEnhance?: boolean }): Promise<{
    success: boolean;
    functions_found: number;
    embedding_generated: boolean;
  }> {
    return this.client.restPost(`/api/apps/${encodeURIComponent(appId)}/generate-docs`, {
      ai_enhance: options?.aiEnhance,
    }) as Promise<{
      success: boolean;
      functions_found: number;
      embedding_generated: boolean;
    }>;
  }

  /**
   * Get app documentation
   */
  async get(appId: string, format?: 'markdown' | 'json' | 'mcp'): Promise<{
    exists: boolean;
    skills_md?: string;
    skills_parsed?: unknown;
    tools?: unknown[];
  }> {
    if (format === 'mcp') {
      const instructions = await this.client.restText(`/api/apps/${encodeURIComponent(appId)}/instructions`);
      return { exists: true, skills_md: instructions };
    }

    const skillsMd = await this.client.restText(`/api/apps/${encodeURIComponent(appId)}/skills.md`);
    return { exists: true, skills_md: skillsMd };
  }

  /**
   * Update app documentation
   */
  async update(appId: string, skillsMd: string): Promise<{
    success: boolean;
    functions_found: number;
    warnings: string[];
  }> {
    return this.client.restPatch(`/api/apps/${encodeURIComponent(appId)}/skills`, {
      skills_md: skillsMd,
    }) as Promise<{
      success: boolean;
      functions_found: number;
      warnings: string[];
    }>;
  }
}

/**
 * MCP client for calling app-specific tools
 */
class McpClient {
  private requestId = 0;

  constructor(
    private apiUrl: string,
    private token: string,
    private appId: string
  ) {}

  /**
   * List available tools for this app
   */
  async listTools(): Promise<McpTool[]> {
    const response = await this.request('tools/list', {});
    return (response as { tools: McpTool[] }).tools;
  }

  /**
   * Call a tool on this app
   */
  async callTool(name: string, args: Record<string, unknown>): Promise<unknown> {
    const response = await this.request('tools/call', {
      name,
      arguments: args,
    });

    if ((response as { isError?: boolean }).isError) {
      throw new UltralightError((response as { content?: Array<{ text?: string }> }).content?.[0]?.text || 'Tool error');
    }

    return (response as { structuredContent?: unknown }).structuredContent;
  }

  private async request(method: string, params: Record<string, unknown>): Promise<unknown> {
    const response = await fetch(`${this.apiUrl}/mcp/${this.appId}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.token}`,
      },
      body: JSON.stringify({
        jsonrpc: '2.0',
        id: ++this.requestId,
        method,
        params,
      }),
    });

    if (!response.ok) {
      throw new UltralightError(`API error: ${response.status}`, response.status);
    }

    const rpc = await response.json() as JsonRpcResponse;

    if (rpc.error) {
      throw new UltralightError(rpc.error.message, rpc.error.code);
    }

    return rpc.result;
  }
}

/**
 * Custom error class for Ultralight SDK
 */
export class UltralightError extends Error {
  constructor(message: string, public code?: number) {
    super(message);
    this.name = 'UltralightError';
  }
}

// Default export
export default Ultralight;
